baseURL = "https://kross.beyerham.com"
languageCode = "en-au"
summaryLength = "10"
theme = "kross-hugo"
title = "Meet the Beyerhams"
[params]
address = ""
author = "Johnathan Smith"
copyright = "Thanks to [gethugothemes](https://gethugothemes.com) for the website theme"
description = "Why hyphenate when you can create a portmanteau? This unfamiliar last name is a blend of Beyer and Pinkham, used for the first time with Adelaide Beyerham"
email = ""
google_analytics_id = ""
home = ""
logo = ""
phone = ""
social = []
theme_color = "#41228e"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
