baseURL = "https://kross.beyerham.com"
languageCode = "en-au"
summaryLength = "10"
theme = "kross-hugo"
title = "Meet the Beyerhams"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "125/A, CA Commercial Area, California, USA"
author = "Johnathan Smith"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "The last name combining \"Beyer\" and \"Pinkham\" for the lovely new addition to the world, Adelaide Beyerham"
email = ""
google_analytics_id = ""
home = "Home"
logo = ""
phone = "+880 2544 658 256"
social = []
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
